# This file tells Netlify how to build and serve your site.

[build]
  # This is the command to build your React app for production.
  command = "npm run build"
  # This is the folder where the built site will be.
  publish = "dist"
  # This tells Netlify where your serverless functions are.
  functions = "api/"

# This rule makes sure that your React app handles all page routing correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
